server:
  port: 9000
spring:
  application:
    name: JRTP-Map_The_SSN_To_State_Name
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Tara
    url: jdbc:mysql://localhost:3306/jrtpssn
    username: root
  jpa:
    show-sql: true
